add Tool schemas
Tofixrs/SM-JSON-Schemas pull request #9
Opened 2024-03-23 05:52 UTC by Natejoestev

I added schemas for tools

2024-03-25 20:17 UTC, Tofixrs requested changes

2024-03-25 20:17 UTC, Tofixrs commented on toolSet.json
> +                            }
```suggestion
                            "class": {
                                "type": "string",
                                "description": "Name of the class in the script file"
                            },
                            "data": {
                                "type": "string",
                                "description": "description": "Additional data provided to the script available under self.data"
                            }
```

2024-03-25 20:17 UTC, Tofixrs commented on README.md
> +- idk if tool scripts can have `data`
```suggestion
```

2024-03-26 00:28 UTC, Natejoestev commented on toolSet.json
> +                            }
data is not a string.? it's an object

2024-03-26 20:45 UTC, Tofixrs approved these changes

2024-03-26 20:45 UTC, merged